version: "3.9"

# Services
services:

  etl:
    image: "python:3.9"
    build: etl/
    volumes:
      - './etl/:/app'
    depends_on:
      - database

  database:
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5555:5432"
#    volumes:
#      - "./database:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
