version: "3.9"

# Services
services:


  database:
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "./database:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready -d postgres -U username"]
      interval: 10s
      timeout: 5s
      retries: 5

  
  etl:
    image: "python:3.9"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/src'
    depends_on:
      - database
    links:
      - database


# Volumes
volumes:
  database:
    driver: local